#!/usr/bin/env node
/**
 * Weekly Summary CLI Report
 * Prints the current (or specified) week's summary to the terminal.
 *
 * Usage:
 *   npm run report                  # current week
 *   npm run report -- --week 2024-01-08   # specific week (must be a Monday)
 */

import Database from "better-sqlite3";
import path from "path";
import os from "os";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DB_PATH = path.join(os.homedir(), ".weekly-pulse", "weekly-pulse.db");
const SCHEMA_PATH = path.join(__dirname, "../src/lib/db/schema.sql");

// ─── Date Helpers ──────────────────────────────────────────────────────────────

function getWeekStart(date = new Date()) {
  const d = new Date(date);
  const day = d.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  d.setDate(d.getDate() + diff);
  return d.toISOString().slice(0, 10);
}

function formatDate(isoStr) {
  const d = new Date(isoStr + "T12:00:00");
  return d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
}

function addDays(isoStr, n) {
  const d = new Date(isoStr + "T12:00:00");
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

// ─── Parse args ───────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
let weekArg = null;
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--week" && args[i + 1]) weekArg = args[i + 1];
}
const weekStart = weekArg ?? getWeekStart();
const weekEnd = addDays(weekStart, 6);

// ─── Load DB ──────────────────────────────────────────────────────────────────

let db;
try {
  db = new Database(DB_PATH, { readonly: true });
} catch {
  console.error(`\n❌ Cannot open database at ${DB_PATH}`);
  console.error("   Run the dashboard first: npm run dev\n");
  process.exit(1);
}

// ─── Fetch data ───────────────────────────────────────────────────────────────

const entries = db
  .prepare("SELECT * FROM log_entries WHERE week_start = ? ORDER BY entry_date ASC, created_at ASC")
  .all(weekStart);

const calEvents = db
  .prepare("SELECT * FROM calendar_events WHERE week_start = ? ORDER BY start_time ASC")
  .all(weekStart);

const highlights = entries.filter((e) => e.type === "highlight");
const lowlights = entries.filter((e) => e.type === "lowlight");
const blockers = entries.filter((e) => e.type === "blocker");

const activeDays = new Set([
  ...entries.map((e) => e.entry_date),
  ...calEvents.map((e) => e.entry_date),
]);

// ─── Print ────────────────────────────────────────────────────────────────────

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const BLUE = "\x1b[34m";
const CYAN = "\x1b[36m";

function section(title, items, color, emoji) {
  if (!items.length) return;
  console.log(`\n${BOLD}${color}${emoji}  ${title}${RESET}`);
  console.log(`${DIM}${"─".repeat(40)}${RESET}`);
  for (const item of items) {
    const src = item.source !== "manual" ? ` ${DIM}(${item.source})${RESET}` : "";
    console.log(`  ${color}•${RESET} ${item.content}${src}`);
  }
}

const weekStartFmt = formatDate(weekStart);
const weekEndFmt = formatDate(weekEnd);

console.log(`\n${BOLD}${CYAN}WEEKLY PULSE — ${weekStartFmt} → ${weekEndFmt}${RESET}`);
console.log(`${"═".repeat(50)}`);

if (entries.length === 0 && calEvents.length === 0) {
  console.log(`\n${DIM}  No entries logged for this week.${RESET}\n`);
  process.exit(0);
}

// Stats
console.log(
  `\n  ${GREEN}${highlights.length} highlights${RESET}  ` +
    `${YELLOW}${lowlights.length} lowlights${RESET}  ` +
    `${RED}${blockers.length} blockers${RESET}  ` +
    `${BLUE}${calEvents.length} meetings${RESET}  ` +
    `${DIM}${activeDays.size} active days${RESET}`
);

section("Highlights", highlights, GREEN, "✅");
section("Lowlights", lowlights, YELLOW, "⚠️ ");
section("Blockers", blockers, RED, "🚫");

if (calEvents.length > 0) {
  console.log(`\n${BOLD}${BLUE}📅  Meetings${RESET}`);
  console.log(`${DIM}${"─".repeat(40)}${RESET}`);
  for (const ev of calEvents) {
    const attendees = ev.attendee_count > 0 ? ` ${DIM}(${ev.attendee_count} attendees)${RESET}` : "";
    console.log(`  ${BLUE}•${RESET} ${ev.title}${attendees}`);
  }
}

console.log(`\n${DIM}Generated by Weekly Summary · ${new Date().toLocaleString()}${RESET}\n`);
